# Quick test configuration - minimal runtime
name: test_quick
description: Quick test run for validating config system

grid:
  Nx: 32
  Ny: 32
  Nz: 16
  Lx: 6.283185307179586
  Ly: 6.283185307179586
  Lz: 6.283185307179586

physics:
  v_A: 1.0
  eta: 0.01
  nu: 0.01
  beta_i: 1.0
  hyper_r: 1
  hyper_n: 1

initial_condition:
  type: random_spectrum
  amplitude: 0.5
  alpha: 1.6666666666666667
  k_min: 1.0
  k_max: 5.0
  M: 10

forcing:
  enabled: false

time_integration:
  n_steps: 10
  cfl_safety: 0.3
  save_interval: 5

io:
  output_dir: output/test_quick
  save_spectra: true
  save_energy_history: true
  save_fields: false
  save_final_state: true
  overwrite: true
